kind: Service
apiVersion: v1
metadata:
  name: shopping-cart-service
  namespace: namespace1
spec:
  selector:
    app: shopping-cart-service
  ports:
  - protocol: TCP
    port: 8090
   # nodePort: 30082
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-service
  namespace: namespace1
spec:
  selector:
      matchLabels:
        app: shopping-cart-service
  replicas: 1
  template:
    metadata:
      labels:
        app: shopping-cart-service
    spec:
      serviceAccountName: default
      containers:
        - name: shopping-cart-service
          image: amit4sun/shopping-cart-service:1.0
          ports:
          - containerPort: 8090
