spring:    
  application:
    name: item-service
  jackson:
    serialization:
      indent-output: true
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
server:
  port: 8090

management:
  endpoint:
    health:
      show-details: always      
  endpoints:
    web:
      exposure:
        include: "*"